sudo: required
language: go
services:
- docker
go:
- 1.12.x
before_install:
- curl -sLo- http://get.bpkg.sh | sudo bash
before_script:
- sudo bpkg install rylnd/shpec
script:
- make test
- make package
- ls -alh nodejs-engine-buildpack-*.tgz
env:
  GO111MODULE: "on"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "nodejs-engine-buildpack-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
  on:
    tags: true
dist: xenial
