sudo: required
language: go
services:
- docker
go:
- 1.14.x
script:
- make test
- make package
- ls -alh nodejs-engine-buildpack-*.tgz
env:
  GO111MODULE: "on"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "nodejs-engine-buildpack-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
  on:
    tags: true
dist: xenial
